---
- name: Install Apache
  apt:
    name: apache2
    state: present

- name: Customize index.html
  template:
    force: true
    src: apache-index.j2 # required. Path of a Jinja2 formatted template on the Ansible controller. This can be a relative or an absolute path. The file must be encoded with C(utf-8) but I(output_encoding) can be used to control the encoding of the output template.
    dest: /var/www/html/index.html # required. Location to render the template to on the remote machine.
  notify: 
    - apache-reloaded

- name: Check if port 80 is listening
  wait_for:
    port: 80
    delay: 5
    timeout: 10
    msg: "Timeout waiting for 80 to respond"
  register: port_check
  ignore_errors: yes

- name: Try to restart httpd if not started
  service: 
    name: httpd
    state: started
    enabled: yes
  when: port_check.failed == true

- name: Check for code 200
  uri:
    url: "http://{{ inventory_hostname }}"
    method: GET
    status_code: 200
    return_content: no
  register: result
  until: result.status == 200
  retries: 5
  delay: 1