---
- name: Playbook 7-1-2-3-1
  hosts: my
  become: true
  become_user: root
  become_method: sudo
  roles:
    - roles: apache-install
      
  tasks:
    - name: Install Apache
      apt:
        update_cache: true
        name: Apache
        state: present
            
...
