---
- name: Playbook 7-1-2-1-3
  hosts: my
  become: true
  become_user: root
  become_method: sudo
  vars_files: ./vars/motd.yml
  
  tasks:
    - name: Copy using inline content
      ansible.builtin.copy:
        content: "{{ motd }}"
        dest: /etc/motd    
         
...