---
- name: Playbook 7-1-2-1-2
  hosts: my
   
  tasks:
    - name: packages | ensure apt list dir exists
      file:
        path: /var/lib/apt/lists/
        state: directory
        mode: 0755
    
    - name: Install app
      apt:
        name: tuned
        state: present
        update_cache: yes
    
    - name: Start app tuned
      ansible.builtin.service:
        name: tuned
        state: started  

    - name: making autorun app tuned
      ansible.builtin.systemd:
        name: tuned 
        state: started
        enabled: true
   
...