---
- name: Playbook 7-1-2-1-2
  hosts: my
  become: true
  become_user: root
  become_method: sudo
  
  tasks:
#    - name: packages | ensure apt list dir exists
#      file:
#        path: /var/lib/apt/lists/lock
#        state: file
#        mode: 0644
   
    - name: Install app
      apt:
        update_cache: true
        name: tuned
        state: present
                
    - name: Start app tuned
      ansible.builtin.service:
        name: tuned
        state: started
      
    - name: making autorun app tuned
      ansible.builtin.systemd:
        name: tuned 
        state: started
        enabled: true
         
...